# Generated by Django 4.2.6 on 2025-06-07 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role_follower_follower_unique_follower'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follower',
            new_name='Follow',
        ),
        migrations.RenameIndex(
            model_name='follow',
            new_name='accounts_fo_from_us_fb803c_idx',
            old_name='accounts_fo_from_us_d006da_idx',
        ),
    ]
