FROM node:18-alpine

WORKDIR /app

# Only copy files related to package installation
COPY package.json package-lock.json ./


# Install packages
RUN npm install



# These two are necessary for hot-reload in development mode
ENV WATCHPACK_POLLING=true
ENV CHOKIDAR_USEPOLLING=true



# Copy the remaining files (they will be overridden in the volume, but that's fine)
COPY . .

EXPOSE 3000


CMD ["npm", "run", "dev"]

