version: '3.8'

services:
  redis:
    container_name: redis-blog-react
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  backend:
    build: ./backend
    container_name: backend-blog-react
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
    command: python manage.py runserver 0.0.0.0:8000
    depends_on: 
      - redis

  worker:
    build: ./backend
    command: celery -A core worker --loglevel=info
    depends_on:
      - redis
      - backend
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontEnd
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontEnd:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
