# Generated by Django 4.2.6 on 2025-06-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='display_priority',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
