# Generated by Django 4.2.6 on 2025-06-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('FOLLOW', 'Follow'), ('COMMENT', 'Comment'), ('COMMENT_LIKE', 'Comment Like'), ('LIKE', 'Like')], help_text='Type of notification', max_length=20),
        ),
    ]
