# Generated by Django 4.2.6 on 2025-06-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('FOLLOW', 'Follow'), ('COMMENT', 'Comment'), ('COMMENT_LIKE', 'Comment Like'), ('LIKE', 'Like'), ('PUBLISH', 'Post Published')], help_text='Type of notification', max_length=20),
        ),
    ]
