# Generated by Django 4.2.6 on 2023-10-21 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category name')),
                ('body', models.TextField(blank=True, null=True, verbose_name='cat body')),
                ('img', models.ImageField(blank=True, null=True, upload_to='category_image/')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Post title')),
                ('slug', models.SlugField()),
                ('body', models.TextField(verbose_name='Post body')),
                ('tags', models.TextField(blank=True, help_text='sperte wvery tags wih , and tab ', null=True)),
                ('status', models.BooleanField(default=False)),
                ('img', models.ImageField(blank=True, null=True, upload_to='blog_image/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='posts.author')),
                ('categories', models.ManyToManyField(blank=True, related_name='posts_category', to='posts.category')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
