# Generated by Django 4.2.6 on 2023-10-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_bloglike'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloglike',
            name='like_status',
            field=models.BooleanField(default=False),
        ),
    ]
