# Generated by Django 4.2.6 on 2023-10-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='viewed_ips',
            field=models.TextField(blank=True),
        ),
    ]
