# Generated by Django 4.2.6 on 2025-06-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_publish_time_alter_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='The actual time when the post went live', null=True, verbose_name='Published At'),
        ),
    ]
